---
ID: "9e7ff926-f401-4181-af63-46d7394eb475"
Parent: "5f9078f0-ce12-471c-ac50-a8c78e5b6b8a"
Template: "5f9078f0-ce12-471c-ac50-a8c78e5b6b8a"
Path: /sitecore/templates/Project/Company DEV/General Components/Rendering Parameters/TestimonialList/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ba116063-e12b-4749-86e7-38d2501e06c1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Sebastian Winter
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240626T125118Z
