---
ID: "8f189e8a-674e-4a45-a97c-e00f19bbd777"
Parent: "d91663ed-1c62-4d29-b8c1-bcd85d5671d2"
Template: "d91663ed-1c62-4d29-b8c1-bcd85d5671d2"
Path: /sitecore/templates/Project/Company DEV/General Components/Rendering Parameters/SkillsOverview/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "aaa13dd6-fbd1-4017-8cb2-4d69a60e7d40"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Sebastian Winter
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240626T125044Z
