---
ID: "04effca7-4951-440d-bda2-2e3f919b4b89"
Parent: "9a69dbcf-8e7b-43ff-a22a-06da1329774c"
Template: "9a69dbcf-8e7b-43ff-a22a-06da1329774c"
Path: /sitecore/templates/Project/Company DEV/Services/Rendering Parameters/Services Teaser/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "982796d1-c9e6-4a7f-929c-3c261bdb5ba0"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Sebastian Winter
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240513T153459Z
