---
ID: "2a48aeaf-0c9b-43e5-878f-caa2255b752d"
Parent: "d8392938-0ae6-4a3e-8003-28e736627554"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: /sitecore/content/Company DEV/Company DEV/Presentation/Headless Variants/TeamList/Default
BranchID: "5ad645d6-31d4-4f30-b03a-f38106ceccb1"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{BACE4731-0C86-45ED-A0F6-C041BEBD0D6D}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240626T134916Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Sebastian Winter
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Sebastian Winter
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "24896772-ee68-4416-b931-51f76d2efead"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Sebastian Winter
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240626T134916Z
