---
ID: "ec5580c5-99ff-4958-8125-be38ce986b00"
Parent: "acceb4e1-07ce-4424-945d-31898480a013"
Template: "acceb4e1-07ce-4424-945d-31898480a013"
Path: /sitecore/templates/Project/Company DEV/General Components/Rendering Parameters/TeamList/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "387abe29-869a-4057-b9ab-4d058cbc1e8b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Sebastian Winter
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240626T125006Z
